import:
  - ~/.config/alacritty/themes/oxocarbon-dark.yml

font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Medium
  bold:
    family: JetBrainsMono Nerd Font
    style: Bold
  italic:
    family: JetBrainsMono Nerd Font
    style: Italic
  bold_italic:
    family: JetBrainsMono Nerd Font
    style: Bold Italic

  size: 10.0

  offset:
    x: 1
    y: 1

cursor:
  style:
    shape: Beam

window:
  padding:
    x: 10
    y: 10 
