import:
  - ~/.config/alacritty/themes/catpuccin-mocha.yml

font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Medium
  bold:
    family: JetBrainsMono Nerd Font
    style: Bold
  italic:
    family: JetBrainsMono Nerd Font
    style: Italic
  bold_italic:
    family: JetBrainsMono Nerd Font
    style: Bold Italic

  size: 8.0

  offset:
    x: 1
    y: 1

window:
  padding:
    x: 2
    y: 2
