{ pkgs
,inputs
, xdg-hyprland
, ...
}:

{
  home.packages = with pkgs; [
    skim
    ripgrep
    bat
    keepassxc
    grim
    slurp
    libnotify
    swww
    kitty
    dunst
    tealdeer
    adw-gtk3
    rnix-lsp
    ranger
    ueberzug
    bottom
    pamixer
    xfce.thunar
    wl-clipboard
    pavucontrol
    wget
    firefox
    mullvad-browser
    tor-browser-bundle-bin
    ungoogled-chromium
    tangram
    authenticator
    wf-recorder
    glib
    vlc
    unzip
    gparted
    ncmpcpp
    mpd
    tofi
    wlogout
    tty-clock
    playerctl
    qalculate-gtk
    swaylock-effects
    bleachbit
    imv
    libsForQt5.dolphin
    cmatrix
    libreoffice
    cava
    inputs.hyprpicker.packages.${pkgs.system}.hyprpicker
    #inputs.davinciresolve.packages.${pkgs.system}.davinci-resolve
    git
    qbittorrent
    swww
    thunderbird
    android-file-transfer
    nebula
    remmina
    croc
    exa
    jetbrains.phpstorm
    jetbrains.datagrip
    jetbrains.rider
    termscp
    dbeaver
    tutanota-desktop
    yt-dlp
    flyctl
    distrobox
    fzf
    glxinfo
    libsForQt5.kdenlive
    blender
    shotcut
    gimp
    inkscape
    drawio
    webcord
    dig # Tools for diagnosing DNS-related issuse 
  ];
}
